---

- name: Manage route53 Health checks
  route53_health_check:
     aws_access_key: "{{ aws_route53_healthcheck_aws_access_key | default(omit) }}"
     aws_secret_key: "{{ aws_secret_key | default(omit)}}"
     ec2_url: "{{ aws_route53_healthcheck_ec2_url | default(omit) }}"
     failure_threshold: "{{ aws_route53_healthcheck_failure_threshold | default(omit) }}"
     fqdn: "{{ aws_route53_healthcheck_fqdn | default(omit) }}"
     ip_address: "{{ aws_route53_healthcheck_ip_address | default(omit) }}"
     port: "{{ aws_route53_healthcheck_port | default(omit) }}"
     profile: "{{ aws_route53_healthcheck_profile | default(omit) }}"
     region: "{{ aws_route53_healthcheck_region | default(omit) }}"
     request_interval: "{{ aws_route53_healthcheck_request_interval | default(omit) }}"
     resource_path: "{{ aws_route53_healthcheck_resource_path | default(omit) }}"
     security_token: "{{ aws_route53_healthcheck_security_token | default(omit) }}"
     state: "{{ aws_route53_healthcheck_state | default(omit) }}"
     string_match: "{{ aws_route53_healthcheck_string_match | default(omit) }}"
     type: "{{ aws_route53_healthcheck_type | default(omit) }}"
     validate_certs: "{{ aws_route53_healthcheck_validate_certs | default(omit) }}"
  register: aws_route53_healthcheck_output
  when: aws_route53_healthcheck_enabled
  connection: local
  delegate_to: localhost

- name: Add Healthcheck records to AWS route53
  route53:
      command: "{{ item.command | default('create') }}"
      zone: "{{ item.zone | default(omit) }}"
      record: "{{ item.record }}"
      ttl: "{{ item.ttl | default('30') }}"
      type: "{{ item.type | default('A') }}"
      value: "{{ item.value | default(aws_route53_healthcheck_record_value) }}"
      overwrite: "{{ item.overwrite | default('true') }}"
      retry_interval: "{{ item.retry | default(omit) }}"
      weight: "{{ item.weight | default(1) }}"
      identifier: "{{ aws_route53_healthcheck_identifier | default(inventory_hostname) }}"
      health_check: "{{ aws_route53_healthcheck_output.health_check.id if aws_route53_healthcheck_enabled else omit }}"
  with_items: "{{ aws_route53_healthcheck_route53_value }}"
  when: aws_route53_healthcheck_route53_value | default("") != ""
  connection: local
  delegate_to: localhost
